version: "3.4"
services:
  app:
    build: 
      context: .
      target: app
      args:
        LATEST_COMMIT_SHA: ${LATEST_COMMIT_SHA}
    ports:
      - "5000:5000"
  test:
    build:
      context: .
      target: test